# 공공데이터 포털 서비스 인증키
# URL 인코딩된 형태로 저장

# Se 서비스키
api.service.key.se=hPrdpbOAuU8ouxUCNFQ%2B3GhU1eshPcqvNhYV2QamRDzm3Vg32RGIpuEj5jaAGt8AQxVjdhdN5vgymQb6fh6y1w%3D%3D

# Bo 서비스키
api.service.key.bo=UW9L4iVc%2FhRefJdmBeANqq0YpvU1yhx3LHbUSNmSHeZznF70k04tfNjZbpFnasBOtEr1hGTHpkqS9i8zEYUUsQ%3D%3D

# Wa 서비스키
api.service.key.wa=QZqnwRRbk91dk1rSfVmLByXYHxG5LXUX03kbhu31XCqODQh1%2BJAgNigVraqO%2F1sEZtE3mOCC6FV4JZjPXy73xw%3D%3D

# Ju 서비스키
api.service.key.ju=%2FBstLSrHchiOl50E4qyAJirb9PM6IhUV1UmaAlefvEfRvM4YLQplX1A0UGtet0vi44M21gibI4l3ldPUz9lQMA%3D%3D

# Ja 서비스키 (GetAPIData.java에서 사용)
api.service.key.default=gxF3vfrb%2FWP6p4M7q4vJqTpmSyZQogbuDVs4U98InkzW4uD7lV0STqbC5BDflGo4im41%2FXxSd97oH1jEUkORUw%3D%3D

# 카카오 API 키
api.kakao.map.appkey=10cb881534fe9be97e2db4854bde4bf1
api.kakao.js.key=e8b842dc97356296e338660ae4063b8a
api.kakao.rest.key=f08deb4abc2cec584eecade447daf3bf
api.kakao.mobile.key=41924af6fe5d95bebf4d8ddf6fca8d8c

# 네이버 API 키
api.naver.client.id=02aFSrv2E53MWqQAERSx
api.naver.client.secret=48ZDNX7Aeo

