index=toour.action.IndexAction
sido=toour.action.sidoAction
findWay=toour.action.KakaoMobilAction
GoWay=toour.action.FindWayGoAction

signup=toour.login.action.SignUpAction
login=toour.login.action.loginAction
chkid=toour.login.action.chkIdAction
chkpw=toour.login.action.chkPwAction
chknickname=toour.login.action.chkNicknameAction
chkemail=toour.login.action.chkEmailAction
moveLogin=toour.login.action.moveLoginAction
moveSignup=toour.login.action.moveSignupAction
kakaoLogin=toour.login.action.KakaoLoginAction
kakaologout=toour.login.action.KakaoLogoutAction

list=toour.post.action.ListAction
edit=toour.post.action.EditAction
write=toour.post.action.WriteAction
view=toour.post.action.ViewAction
saveImg=toour.post.action.SaveImgAction
postSearch=toour.post.action.postSearchAction
comment = toour.post.action.CommentAction
del = toour.post.action.DeleteAction

searchKeyword=toour.search.action.SearchSuggestionAction
apiSearchPaging=toour.search.action.ApiSearchPagingAction
searchResult=toour.action.SearchResultAction


tripSuggestion=toour.tripsuggestion.action.tripSuggestionAction
area=toour.tripsuggestion.action.AreaAction
tripDetails=toour.tripsuggestion.action.tripDetailsAction
tripPaging=toour.tripsuggestion.action.tripPagingAction
courseDetails=toour.tripsuggestion.action.courseDetailsAction
sidoDetails=toour.tripsuggestion.action.sidoDetailsAction


notice=toour.notice.action.NoticeListAction
NoticeSearch=toour.notice.action.NoticeSearchAction
noticeview = toour.notice.action.NoticeViewAction

mypage=toour.member.action.myPageAction
mypost=toour.member.action.post.myPostAction
mypostsearch=toour.member.action.myPostSearchAction
addDeleteZzim=toour.member.action.addDeleteZzimAction


QnA=toour.post.action.QnAAction
inquiryList=toour.post.action.InquiryListAction
inquiryView=toour.post.action.InquiryViewAction
inquirySearch=toour.post.action.InquirySearchAction