list=toour.action.ListAction
signup=toour.action.SignUpAction
index=toour.action.indexAction
login=toour.action.loginAction
chkid=toour.action.chkIdAction
chkpw=toour.action.chkPwAction
chkemail=toour.action.chkEmailAction
adminmemlist=toour.action.mem.MemViewAction


