
list=toour.post.action.ListAction
signup=toour.login.action.SignUpAction
index=toour.action.IndexAction
login=toour.login.action.loginAction
chkid=toour.login.action.chkIdAction
chkpw=toour.login.action.chkPwAction
chknickname=toour.login.action.chkNicknameAction
chkemail=toour.login.action.chkEmailAction

adminmemlist=toour.action.mem.MemListAction
adminmemview=toour.action.mem.MemViewAction
adminmemedit=toour.action.mem.MemEditAction
adminmemdel = toour.action.mem.MemDelAction


edit=toour.post.action.EditAction
write=toour.post.action.WriteAction
sido=toour.action.sidoAction
view=toour.post.action.ViewAction

tripSuggestion=toour.tripsuggestion.action.tripSuggestionAction
contentType=toour.action.contentTypeAction

postSearch=toour.post.action.postSearchAction
headSearch=toour.action.HeaderSearchAction
notice=toour.notice.action.NoticeListAction
noticeSearch=toour.notice.action.NoticeSearchAction


test=toour.action.testAction
