adminmemlist=toour.member.action.MemListAction
adminmemview=toour.member.action.MemViewAction
adminmemedit=toour.member.action.MemEditAction
adminmemdel = toour.member.action.MemDelAction
adminmeminfo = toour.member.action.AdminMemInfoAction
adminmemsearch = toour.member.action.AdminMemSearchAction


adminnotice = toour.member.action.AdminNotice
adminnoticeview = toour.member.action.AdminNoticeViewAction
adminnoticeedit = toour.member.action.AdminNoticeEditAction
adminnoticewrite = toour.member.action.AdminNoticeWriteAction
adminnoticedel = toour.member.action.AdminNoticeDelAction
adminnoticesaveimg = toour.member.action.AdminNoticeSaveImgAction
adminnoticesearch = toour.member.action.AdminNoticeSearchAction

adminpost = toour.member.action.post.AdminPostListAction
adminpostwrite = toour.member.action.post.AdminPostWriteAction
adminpostview = toour.member.action.post.AdminPostViewAction
adminpostedit = toour.member.action.post.AdminPostEditAction
adminpostdel = toour.member.action.post.AdminPostDelAction
adminpostsaveimg = toour.member.action.post.AdminPostSaveImgAction
adminpostsearch = toour.member.action.post.AdminPostSearchAction


adminInquiry=toour.member.action.post.adminInquiryAction

AdminMain = toour.member.action.AdminMainAction

adminReport= toour.admin.action.AdminReportAction

AdminPostChart=toour.member.action.AdminPostChartAction